stages:
  - compile
  - docs


###########
## BUILD ##
###########
compile-elm:
  stage: compile
  tags:
    - elm
  before_script:
    - source /etc/profile
  script:
    - rm -rf ./elm-stuff/
    - make
  only:
    - master
    - /^\d*-.*/


compile-docs:
  stage: docs
  tags:
    - elm
  before_script:
    - source /etc/profile
  script:
    - rm -rf ./elm-stuff/
    - make docs
  only:
    - master
    - /^\d*-.*/

